/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UrlCheckRouteImport } from './routes/url-check'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as TrustedRouteImport } from './routes/trusted'
import { Route as TipsRouteImport } from './routes/tips'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as ResultRouteImport } from './routes/result'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PermissionsRouteImport } from './routes/permissions'
import { Route as PairRouteImport } from './routes/pair'
import { Route as LanguageRouteImport } from './routes/language'
import { Route as HomeRouteImport } from './routes/home'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as EducationRouteImport } from './routes/education'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as IndexRouteImport } from './routes/index'

const UrlCheckRoute = UrlCheckRouteImport.update({
  id: '/url-check',
  path: '/url-check',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const TrustedRoute = TrustedRouteImport.update({
  id: '/trusted',
  path: '/trusted',
  getParentRoute: () => rootRouteImport,
} as any)
const TipsRoute = TipsRouteImport.update({
  id: '/tips',
  path: '/tips',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultRoute = ResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PermissionsRoute = PermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => rootRouteImport,
} as any)
const PairRoute = PairRouteImport.update({
  id: '/pair',
  path: '/pair',
  getParentRoute: () => rootRouteImport,
} as any)
const LanguageRoute = LanguageRouteImport.update({
  id: '/language',
  path: '/language',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const EducationRoute = EducationRouteImport.update({
  id: '/education',
  path: '/education',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/community': typeof CommunityRoute
  '/dashboard': typeof DashboardRoute
  '/education': typeof EducationRoute
  '/history': typeof HistoryRoute
  '/home': typeof HomeRoute
  '/language': typeof LanguageRoute
  '/pair': typeof PairRoute
  '/permissions': typeof PermissionsRoute
  '/privacy': typeof PrivacyRoute
  '/result': typeof ResultRoute
  '/scan': typeof ScanRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/tips': typeof TipsRoute
  '/trusted': typeof TrustedRoute
  '/upload': typeof UploadRoute
  '/url-check': typeof UrlCheckRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/community': typeof CommunityRoute
  '/dashboard': typeof DashboardRoute
  '/education': typeof EducationRoute
  '/history': typeof HistoryRoute
  '/home': typeof HomeRoute
  '/language': typeof LanguageRoute
  '/pair': typeof PairRoute
  '/permissions': typeof PermissionsRoute
  '/privacy': typeof PrivacyRoute
  '/result': typeof ResultRoute
  '/scan': typeof ScanRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/tips': typeof TipsRoute
  '/trusted': typeof TrustedRoute
  '/upload': typeof UploadRoute
  '/url-check': typeof UrlCheckRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/community': typeof CommunityRoute
  '/dashboard': typeof DashboardRoute
  '/education': typeof EducationRoute
  '/history': typeof HistoryRoute
  '/home': typeof HomeRoute
  '/language': typeof LanguageRoute
  '/pair': typeof PairRoute
  '/permissions': typeof PermissionsRoute
  '/privacy': typeof PrivacyRoute
  '/result': typeof ResultRoute
  '/scan': typeof ScanRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/tips': typeof TipsRoute
  '/trusted': typeof TrustedRoute
  '/upload': typeof UploadRoute
  '/url-check': typeof UrlCheckRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/community'
    | '/dashboard'
    | '/education'
    | '/history'
    | '/home'
    | '/language'
    | '/pair'
    | '/permissions'
    | '/privacy'
    | '/result'
    | '/scan'
    | '/security'
    | '/settings'
    | '/tips'
    | '/trusted'
    | '/upload'
    | '/url-check'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/community'
    | '/dashboard'
    | '/education'
    | '/history'
    | '/home'
    | '/language'
    | '/pair'
    | '/permissions'
    | '/privacy'
    | '/result'
    | '/scan'
    | '/security'
    | '/settings'
    | '/tips'
    | '/trusted'
    | '/upload'
    | '/url-check'
  id:
    | '__root__'
    | '/'
    | '/community'
    | '/dashboard'
    | '/education'
    | '/history'
    | '/home'
    | '/language'
    | '/pair'
    | '/permissions'
    | '/privacy'
    | '/result'
    | '/scan'
    | '/security'
    | '/settings'
    | '/tips'
    | '/trusted'
    | '/upload'
    | '/url-check'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CommunityRoute: typeof CommunityRoute
  DashboardRoute: typeof DashboardRoute
  EducationRoute: typeof EducationRoute
  HistoryRoute: typeof HistoryRoute
  HomeRoute: typeof HomeRoute
  LanguageRoute: typeof LanguageRoute
  PairRoute: typeof PairRoute
  PermissionsRoute: typeof PermissionsRoute
  PrivacyRoute: typeof PrivacyRoute
  ResultRoute: typeof ResultRoute
  ScanRoute: typeof ScanRoute
  SecurityRoute: typeof SecurityRoute
  SettingsRoute: typeof SettingsRoute
  TipsRoute: typeof TipsRoute
  TrustedRoute: typeof TrustedRoute
  UploadRoute: typeof UploadRoute
  UrlCheckRoute: typeof UrlCheckRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/url-check': {
      id: '/url-check'
      path: '/url-check'
      fullPath: '/url-check'
      preLoaderRoute: typeof UrlCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trusted': {
      id: '/trusted'
      path: '/trusted'
      fullPath: '/trusted'
      preLoaderRoute: typeof TrustedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tips': {
      id: '/tips'
      path: '/tips'
      fullPath: '/tips'
      preLoaderRoute: typeof TipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result': {
      id: '/result'
      path: '/result'
      fullPath: '/result'
      preLoaderRoute: typeof ResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/permissions': {
      id: '/permissions'
      path: '/permissions'
      fullPath: '/permissions'
      preLoaderRoute: typeof PermissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pair': {
      id: '/pair'
      path: '/pair'
      fullPath: '/pair'
      preLoaderRoute: typeof PairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/language': {
      id: '/language'
      path: '/language'
      fullPath: '/language'
      preLoaderRoute: typeof LanguageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/education': {
      id: '/education'
      path: '/education'
      fullPath: '/education'
      preLoaderRoute: typeof EducationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CommunityRoute: CommunityRoute,
  DashboardRoute: DashboardRoute,
  EducationRoute: EducationRoute,
  HistoryRoute: HistoryRoute,
  HomeRoute: HomeRoute,
  LanguageRoute: LanguageRoute,
  PairRoute: PairRoute,
  PermissionsRoute: PermissionsRoute,
  PrivacyRoute: PrivacyRoute,
  ResultRoute: ResultRoute,
  ScanRoute: ScanRoute,
  SecurityRoute: SecurityRoute,
  SettingsRoute: SettingsRoute,
  TipsRoute: TipsRoute,
  TrustedRoute: TrustedRoute,
  UploadRoute: UploadRoute,
  UrlCheckRoute: UrlCheckRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
